apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mon-app2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitlab.gitlab.local/root/mmahfoud.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev