# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 30000

  #Node Master (Controller)
  config.vm.define "mmahfoudS" do |controller|
    controller.vm.hostname = "mmahfoudS"
    controller.vm.network "private_network", ip: "192.168.56.110"
    controller.vm.synced_folder "./vagrant_apps", "/vagrant_apps"
    # Customize the amount of memory on the VM:
    controller.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    
    controller.vm.provision "shell", name: "configS", path: "configS.sh"
  end
end

