# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.boot_timeout = 300

  #Node Master (Controller)
  config.vm.define "mmahfoudS" do |controller|
    controller.vm.hostname = "mmahfoudS"
    controller.vm.network "private_network", ip: "192.168.56.110"
    # Customize the amount of memory on the VM:
    # il se passe quoi si je met pas de memoire ou de cpus
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    controller.vm.provision "shell", name: "configS", path: "scripts/configS.sh"
  end

  config.vm.define "mmahfoudSW" do |agent|
    agent.vm.hostname = "mmahfoudSW"
    agent.vm.network "private_network", ip: "192.168.56.111"
    agent.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    agent.vm.provision "shell", name: "configSW", path: "scripts/configSW.sh"
  end
end
